package cn.yokaya.invoice.db.dao;

import cn.yokaya.invoice.db.entity.Detail;
import cn.yokaya.invoice.db.entity.DetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	long countByExample(DetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	int deleteByExample(DetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	int deleteByPrimaryKey(Integer seq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	int insert(Detail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	int insertSelective(Detail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	List<Detail> selectByExample(DetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	Detail selectByPrimaryKey(Integer seq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Detail record, @Param("example") DetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	int updateByExample(@Param("record") Detail record, @Param("example") DetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	int updateByPrimaryKeySelective(Detail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	int updateByPrimaryKey(Detail record);
}