package cn.yokaya.invoice.db.dao;

import cn.yokaya.invoice.db.entity.Detail1;
import cn.yokaya.invoice.db.entity.Detail1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Detail1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    long countByExample(Detail1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    int deleteByExample(Detail1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    int deleteByPrimaryKey(Integer seq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    int insert(Detail1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    int insertSelective(Detail1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    List<Detail1> selectByExample(Detail1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    Detail1 selectByPrimaryKey(Integer seq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Detail1 record, @Param("example") Detail1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    int updateByExample(@Param("record") Detail1 record, @Param("example") Detail1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    int updateByPrimaryKeySelective(Detail1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    int updateByPrimaryKey(Detail1 record);
}