package cn.yokaya.invoice.db.entity;

import java.math.BigDecimal;

public class Detail1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.seq
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.invoice_seq
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private Integer invoiceSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.xmmc
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private String xmmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.cph
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private String cph;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.lx
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private String lx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.rqq
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private String rqq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.rqz
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private String rqz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.je
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private BigDecimal je;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.sl
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private BigDecimal sl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail1.se
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    private BigDecimal se;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.seq
     *
     * @return the value of detail1.seq
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.seq
     *
     * @param seq the value for detail1.seq
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.invoice_seq
     *
     * @return the value of detail1.invoice_seq
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public Integer getInvoiceSeq() {
        return invoiceSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.invoice_seq
     *
     * @param invoiceSeq the value for detail1.invoice_seq
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setInvoiceSeq(Integer invoiceSeq) {
        this.invoiceSeq = invoiceSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.xmmc
     *
     * @return the value of detail1.xmmc
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public String getXmmc() {
        return xmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.xmmc
     *
     * @param xmmc the value for detail1.xmmc
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setXmmc(String xmmc) {
        this.xmmc = xmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.cph
     *
     * @return the value of detail1.cph
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public String getCph() {
        return cph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.cph
     *
     * @param cph the value for detail1.cph
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setCph(String cph) {
        this.cph = cph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.lx
     *
     * @return the value of detail1.lx
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.lx
     *
     * @param lx the value for detail1.lx
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setLx(String lx) {
        this.lx = lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.rqq
     *
     * @return the value of detail1.rqq
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public String getRqq() {
        return rqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.rqq
     *
     * @param rqq the value for detail1.rqq
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setRqq(String rqq) {
        this.rqq = rqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.rqz
     *
     * @return the value of detail1.rqz
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public String getRqz() {
        return rqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.rqz
     *
     * @param rqz the value for detail1.rqz
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setRqz(String rqz) {
        this.rqz = rqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.je
     *
     * @return the value of detail1.je
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public BigDecimal getJe() {
        return je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.je
     *
     * @param je the value for detail1.je
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setJe(BigDecimal je) {
        this.je = je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.sl
     *
     * @return the value of detail1.sl
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public BigDecimal getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.sl
     *
     * @param sl the value for detail1.sl
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setSl(BigDecimal sl) {
        this.sl = sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail1.se
     *
     * @return the value of detail1.se
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public BigDecimal getSe() {
        return se;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail1.se
     *
     * @param se the value for detail1.se
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setSe(BigDecimal se) {
        this.se = se;
    }
}