package cn.yokaya.invoice.db.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DetailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public DetailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSeqIsNull() {
			addCriterion("seq is null");
			return (Criteria) this;
		}

		public Criteria andSeqIsNotNull() {
			addCriterion("seq is not null");
			return (Criteria) this;
		}

		public Criteria andSeqEqualTo(Integer value) {
			addCriterion("seq =", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotEqualTo(Integer value) {
			addCriterion("seq <>", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThan(Integer value) {
			addCriterion("seq >", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThanOrEqualTo(Integer value) {
			addCriterion("seq >=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThan(Integer value) {
			addCriterion("seq <", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThanOrEqualTo(Integer value) {
			addCriterion("seq <=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqIn(List<Integer> values) {
			addCriterion("seq in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotIn(List<Integer> values) {
			addCriterion("seq not in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqBetween(Integer value1, Integer value2) {
			addCriterion("seq between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotBetween(Integer value1, Integer value2) {
			addCriterion("seq not between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqIsNull() {
			addCriterion("invoice_seq is null");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqIsNotNull() {
			addCriterion("invoice_seq is not null");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqEqualTo(Integer value) {
			addCriterion("invoice_seq =", value, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqNotEqualTo(Integer value) {
			addCriterion("invoice_seq <>", value, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqGreaterThan(Integer value) {
			addCriterion("invoice_seq >", value, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqGreaterThanOrEqualTo(Integer value) {
			addCriterion("invoice_seq >=", value, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqLessThan(Integer value) {
			addCriterion("invoice_seq <", value, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqLessThanOrEqualTo(Integer value) {
			addCriterion("invoice_seq <=", value, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqIn(List<Integer> values) {
			addCriterion("invoice_seq in", values, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqNotIn(List<Integer> values) {
			addCriterion("invoice_seq not in", values, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqBetween(Integer value1, Integer value2) {
			addCriterion("invoice_seq between", value1, value2, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andInvoiceSeqNotBetween(Integer value1, Integer value2) {
			addCriterion("invoice_seq not between", value1, value2, "invoiceSeq");
			return (Criteria) this;
		}

		public Criteria andWwmcIsNull() {
			addCriterion("wwmc is null");
			return (Criteria) this;
		}

		public Criteria andWwmcIsNotNull() {
			addCriterion("wwmc is not null");
			return (Criteria) this;
		}

		public Criteria andWwmcEqualTo(String value) {
			addCriterion("wwmc =", value, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcNotEqualTo(String value) {
			addCriterion("wwmc <>", value, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcGreaterThan(String value) {
			addCriterion("wwmc >", value, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcGreaterThanOrEqualTo(String value) {
			addCriterion("wwmc >=", value, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcLessThan(String value) {
			addCriterion("wwmc <", value, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcLessThanOrEqualTo(String value) {
			addCriterion("wwmc <=", value, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcLike(String value) {
			addCriterion("wwmc like", value, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcNotLike(String value) {
			addCriterion("wwmc not like", value, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcIn(List<String> values) {
			addCriterion("wwmc in", values, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcNotIn(List<String> values) {
			addCriterion("wwmc not in", values, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcBetween(String value1, String value2) {
			addCriterion("wwmc between", value1, value2, "wwmc");
			return (Criteria) this;
		}

		public Criteria andWwmcNotBetween(String value1, String value2) {
			addCriterion("wwmc not between", value1, value2, "wwmc");
			return (Criteria) this;
		}

		public Criteria andGgxhIsNull() {
			addCriterion("ggxh is null");
			return (Criteria) this;
		}

		public Criteria andGgxhIsNotNull() {
			addCriterion("ggxh is not null");
			return (Criteria) this;
		}

		public Criteria andGgxhEqualTo(String value) {
			addCriterion("ggxh =", value, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhNotEqualTo(String value) {
			addCriterion("ggxh <>", value, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhGreaterThan(String value) {
			addCriterion("ggxh >", value, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhGreaterThanOrEqualTo(String value) {
			addCriterion("ggxh >=", value, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhLessThan(String value) {
			addCriterion("ggxh <", value, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhLessThanOrEqualTo(String value) {
			addCriterion("ggxh <=", value, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhLike(String value) {
			addCriterion("ggxh like", value, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhNotLike(String value) {
			addCriterion("ggxh not like", value, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhIn(List<String> values) {
			addCriterion("ggxh in", values, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhNotIn(List<String> values) {
			addCriterion("ggxh not in", values, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhBetween(String value1, String value2) {
			addCriterion("ggxh between", value1, value2, "ggxh");
			return (Criteria) this;
		}

		public Criteria andGgxhNotBetween(String value1, String value2) {
			addCriterion("ggxh not between", value1, value2, "ggxh");
			return (Criteria) this;
		}

		public Criteria andDwIsNull() {
			addCriterion("dw is null");
			return (Criteria) this;
		}

		public Criteria andDwIsNotNull() {
			addCriterion("dw is not null");
			return (Criteria) this;
		}

		public Criteria andDwEqualTo(String value) {
			addCriterion("dw =", value, "dw");
			return (Criteria) this;
		}

		public Criteria andDwNotEqualTo(String value) {
			addCriterion("dw <>", value, "dw");
			return (Criteria) this;
		}

		public Criteria andDwGreaterThan(String value) {
			addCriterion("dw >", value, "dw");
			return (Criteria) this;
		}

		public Criteria andDwGreaterThanOrEqualTo(String value) {
			addCriterion("dw >=", value, "dw");
			return (Criteria) this;
		}

		public Criteria andDwLessThan(String value) {
			addCriterion("dw <", value, "dw");
			return (Criteria) this;
		}

		public Criteria andDwLessThanOrEqualTo(String value) {
			addCriterion("dw <=", value, "dw");
			return (Criteria) this;
		}

		public Criteria andDwLike(String value) {
			addCriterion("dw like", value, "dw");
			return (Criteria) this;
		}

		public Criteria andDwNotLike(String value) {
			addCriterion("dw not like", value, "dw");
			return (Criteria) this;
		}

		public Criteria andDwIn(List<String> values) {
			addCriterion("dw in", values, "dw");
			return (Criteria) this;
		}

		public Criteria andDwNotIn(List<String> values) {
			addCriterion("dw not in", values, "dw");
			return (Criteria) this;
		}

		public Criteria andDwBetween(String value1, String value2) {
			addCriterion("dw between", value1, value2, "dw");
			return (Criteria) this;
		}

		public Criteria andDwNotBetween(String value1, String value2) {
			addCriterion("dw not between", value1, value2, "dw");
			return (Criteria) this;
		}

		public Criteria andCountIsNull() {
			addCriterion("count is null");
			return (Criteria) this;
		}

		public Criteria andCountIsNotNull() {
			addCriterion("count is not null");
			return (Criteria) this;
		}

		public Criteria andCountEqualTo(BigDecimal value) {
			addCriterion("count =", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountNotEqualTo(BigDecimal value) {
			addCriterion("count <>", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountGreaterThan(BigDecimal value) {
			addCriterion("count >", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("count >=", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountLessThan(BigDecimal value) {
			addCriterion("count <", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("count <=", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountIn(List<BigDecimal> values) {
			addCriterion("count in", values, "count");
			return (Criteria) this;
		}

		public Criteria andCountNotIn(List<BigDecimal> values) {
			addCriterion("count not in", values, "count");
			return (Criteria) this;
		}

		public Criteria andCountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("count between", value1, value2, "count");
			return (Criteria) this;
		}

		public Criteria andCountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("count not between", value1, value2, "count");
			return (Criteria) this;
		}

		public Criteria andDjIsNull() {
			addCriterion("dj is null");
			return (Criteria) this;
		}

		public Criteria andDjIsNotNull() {
			addCriterion("dj is not null");
			return (Criteria) this;
		}

		public Criteria andDjEqualTo(BigDecimal value) {
			addCriterion("dj =", value, "dj");
			return (Criteria) this;
		}

		public Criteria andDjNotEqualTo(BigDecimal value) {
			addCriterion("dj <>", value, "dj");
			return (Criteria) this;
		}

		public Criteria andDjGreaterThan(BigDecimal value) {
			addCriterion("dj >", value, "dj");
			return (Criteria) this;
		}

		public Criteria andDjGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("dj >=", value, "dj");
			return (Criteria) this;
		}

		public Criteria andDjLessThan(BigDecimal value) {
			addCriterion("dj <", value, "dj");
			return (Criteria) this;
		}

		public Criteria andDjLessThanOrEqualTo(BigDecimal value) {
			addCriterion("dj <=", value, "dj");
			return (Criteria) this;
		}

		public Criteria andDjIn(List<BigDecimal> values) {
			addCriterion("dj in", values, "dj");
			return (Criteria) this;
		}

		public Criteria andDjNotIn(List<BigDecimal> values) {
			addCriterion("dj not in", values, "dj");
			return (Criteria) this;
		}

		public Criteria andDjBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("dj between", value1, value2, "dj");
			return (Criteria) this;
		}

		public Criteria andDjNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("dj not between", value1, value2, "dj");
			return (Criteria) this;
		}

		public Criteria andJeIsNull() {
			addCriterion("je is null");
			return (Criteria) this;
		}

		public Criteria andJeIsNotNull() {
			addCriterion("je is not null");
			return (Criteria) this;
		}

		public Criteria andJeEqualTo(BigDecimal value) {
			addCriterion("je =", value, "je");
			return (Criteria) this;
		}

		public Criteria andJeNotEqualTo(BigDecimal value) {
			addCriterion("je <>", value, "je");
			return (Criteria) this;
		}

		public Criteria andJeGreaterThan(BigDecimal value) {
			addCriterion("je >", value, "je");
			return (Criteria) this;
		}

		public Criteria andJeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("je >=", value, "je");
			return (Criteria) this;
		}

		public Criteria andJeLessThan(BigDecimal value) {
			addCriterion("je <", value, "je");
			return (Criteria) this;
		}

		public Criteria andJeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("je <=", value, "je");
			return (Criteria) this;
		}

		public Criteria andJeIn(List<BigDecimal> values) {
			addCriterion("je in", values, "je");
			return (Criteria) this;
		}

		public Criteria andJeNotIn(List<BigDecimal> values) {
			addCriterion("je not in", values, "je");
			return (Criteria) this;
		}

		public Criteria andJeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("je between", value1, value2, "je");
			return (Criteria) this;
		}

		public Criteria andJeNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("je not between", value1, value2, "je");
			return (Criteria) this;
		}

		public Criteria andSlIsNull() {
			addCriterion("sl is null");
			return (Criteria) this;
		}

		public Criteria andSlIsNotNull() {
			addCriterion("sl is not null");
			return (Criteria) this;
		}

		public Criteria andSlEqualTo(BigDecimal value) {
			addCriterion("sl =", value, "sl");
			return (Criteria) this;
		}

		public Criteria andSlNotEqualTo(BigDecimal value) {
			addCriterion("sl <>", value, "sl");
			return (Criteria) this;
		}

		public Criteria andSlGreaterThan(BigDecimal value) {
			addCriterion("sl >", value, "sl");
			return (Criteria) this;
		}

		public Criteria andSlGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("sl >=", value, "sl");
			return (Criteria) this;
		}

		public Criteria andSlLessThan(BigDecimal value) {
			addCriterion("sl <", value, "sl");
			return (Criteria) this;
		}

		public Criteria andSlLessThanOrEqualTo(BigDecimal value) {
			addCriterion("sl <=", value, "sl");
			return (Criteria) this;
		}

		public Criteria andSlIn(List<BigDecimal> values) {
			addCriterion("sl in", values, "sl");
			return (Criteria) this;
		}

		public Criteria andSlNotIn(List<BigDecimal> values) {
			addCriterion("sl not in", values, "sl");
			return (Criteria) this;
		}

		public Criteria andSlBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("sl between", value1, value2, "sl");
			return (Criteria) this;
		}

		public Criteria andSlNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("sl not between", value1, value2, "sl");
			return (Criteria) this;
		}

		public Criteria andSeIsNull() {
			addCriterion("se is null");
			return (Criteria) this;
		}

		public Criteria andSeIsNotNull() {
			addCriterion("se is not null");
			return (Criteria) this;
		}

		public Criteria andSeEqualTo(BigDecimal value) {
			addCriterion("se =", value, "se");
			return (Criteria) this;
		}

		public Criteria andSeNotEqualTo(BigDecimal value) {
			addCriterion("se <>", value, "se");
			return (Criteria) this;
		}

		public Criteria andSeGreaterThan(BigDecimal value) {
			addCriterion("se >", value, "se");
			return (Criteria) this;
		}

		public Criteria andSeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("se >=", value, "se");
			return (Criteria) this;
		}

		public Criteria andSeLessThan(BigDecimal value) {
			addCriterion("se <", value, "se");
			return (Criteria) this;
		}

		public Criteria andSeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("se <=", value, "se");
			return (Criteria) this;
		}

		public Criteria andSeIn(List<BigDecimal> values) {
			addCriterion("se in", values, "se");
			return (Criteria) this;
		}

		public Criteria andSeNotIn(List<BigDecimal> values) {
			addCriterion("se not in", values, "se");
			return (Criteria) this;
		}

		public Criteria andSeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("se between", value1, value2, "se");
			return (Criteria) this;
		}

		public Criteria andSeNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("se not between", value1, value2, "se");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table detail
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detail
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 12 17:50:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}