package cn.yokaya.invoice.db.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class Detail1Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public Detail1Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqIsNull() {
            addCriterion("seq is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("seq is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(Integer value) {
            addCriterion("seq =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(Integer value) {
            addCriterion("seq <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(Integer value) {
            addCriterion("seq >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("seq >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(Integer value) {
            addCriterion("seq <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(Integer value) {
            addCriterion("seq <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<Integer> values) {
            addCriterion("seq in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<Integer> values) {
            addCriterion("seq not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(Integer value1, Integer value2) {
            addCriterion("seq between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("seq not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqIsNull() {
            addCriterion("invoice_seq is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqIsNotNull() {
            addCriterion("invoice_seq is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqEqualTo(Integer value) {
            addCriterion("invoice_seq =", value, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqNotEqualTo(Integer value) {
            addCriterion("invoice_seq <>", value, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqGreaterThan(Integer value) {
            addCriterion("invoice_seq >", value, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("invoice_seq >=", value, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqLessThan(Integer value) {
            addCriterion("invoice_seq <", value, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqLessThanOrEqualTo(Integer value) {
            addCriterion("invoice_seq <=", value, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqIn(List<Integer> values) {
            addCriterion("invoice_seq in", values, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqNotIn(List<Integer> values) {
            addCriterion("invoice_seq not in", values, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqBetween(Integer value1, Integer value2) {
            addCriterion("invoice_seq between", value1, value2, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andInvoiceSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("invoice_seq not between", value1, value2, "invoiceSeq");
            return (Criteria) this;
        }

        public Criteria andXmmcIsNull() {
            addCriterion("xmmc is null");
            return (Criteria) this;
        }

        public Criteria andXmmcIsNotNull() {
            addCriterion("xmmc is not null");
            return (Criteria) this;
        }

        public Criteria andXmmcEqualTo(String value) {
            addCriterion("xmmc =", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcNotEqualTo(String value) {
            addCriterion("xmmc <>", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcGreaterThan(String value) {
            addCriterion("xmmc >", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcGreaterThanOrEqualTo(String value) {
            addCriterion("xmmc >=", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcLessThan(String value) {
            addCriterion("xmmc <", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcLessThanOrEqualTo(String value) {
            addCriterion("xmmc <=", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcLike(String value) {
            addCriterion("xmmc like", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcNotLike(String value) {
            addCriterion("xmmc not like", value, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcIn(List<String> values) {
            addCriterion("xmmc in", values, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcNotIn(List<String> values) {
            addCriterion("xmmc not in", values, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcBetween(String value1, String value2) {
            addCriterion("xmmc between", value1, value2, "xmmc");
            return (Criteria) this;
        }

        public Criteria andXmmcNotBetween(String value1, String value2) {
            addCriterion("xmmc not between", value1, value2, "xmmc");
            return (Criteria) this;
        }

        public Criteria andCphIsNull() {
            addCriterion("cph is null");
            return (Criteria) this;
        }

        public Criteria andCphIsNotNull() {
            addCriterion("cph is not null");
            return (Criteria) this;
        }

        public Criteria andCphEqualTo(String value) {
            addCriterion("cph =", value, "cph");
            return (Criteria) this;
        }

        public Criteria andCphNotEqualTo(String value) {
            addCriterion("cph <>", value, "cph");
            return (Criteria) this;
        }

        public Criteria andCphGreaterThan(String value) {
            addCriterion("cph >", value, "cph");
            return (Criteria) this;
        }

        public Criteria andCphGreaterThanOrEqualTo(String value) {
            addCriterion("cph >=", value, "cph");
            return (Criteria) this;
        }

        public Criteria andCphLessThan(String value) {
            addCriterion("cph <", value, "cph");
            return (Criteria) this;
        }

        public Criteria andCphLessThanOrEqualTo(String value) {
            addCriterion("cph <=", value, "cph");
            return (Criteria) this;
        }

        public Criteria andCphLike(String value) {
            addCriterion("cph like", value, "cph");
            return (Criteria) this;
        }

        public Criteria andCphNotLike(String value) {
            addCriterion("cph not like", value, "cph");
            return (Criteria) this;
        }

        public Criteria andCphIn(List<String> values) {
            addCriterion("cph in", values, "cph");
            return (Criteria) this;
        }

        public Criteria andCphNotIn(List<String> values) {
            addCriterion("cph not in", values, "cph");
            return (Criteria) this;
        }

        public Criteria andCphBetween(String value1, String value2) {
            addCriterion("cph between", value1, value2, "cph");
            return (Criteria) this;
        }

        public Criteria andCphNotBetween(String value1, String value2) {
            addCriterion("cph not between", value1, value2, "cph");
            return (Criteria) this;
        }

        public Criteria andLxIsNull() {
            addCriterion("lx is null");
            return (Criteria) this;
        }

        public Criteria andLxIsNotNull() {
            addCriterion("lx is not null");
            return (Criteria) this;
        }

        public Criteria andLxEqualTo(String value) {
            addCriterion("lx =", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotEqualTo(String value) {
            addCriterion("lx <>", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxGreaterThan(String value) {
            addCriterion("lx >", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxGreaterThanOrEqualTo(String value) {
            addCriterion("lx >=", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxLessThan(String value) {
            addCriterion("lx <", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxLessThanOrEqualTo(String value) {
            addCriterion("lx <=", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxLike(String value) {
            addCriterion("lx like", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotLike(String value) {
            addCriterion("lx not like", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxIn(List<String> values) {
            addCriterion("lx in", values, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotIn(List<String> values) {
            addCriterion("lx not in", values, "lx");
            return (Criteria) this;
        }

        public Criteria andLxBetween(String value1, String value2) {
            addCriterion("lx between", value1, value2, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotBetween(String value1, String value2) {
            addCriterion("lx not between", value1, value2, "lx");
            return (Criteria) this;
        }

        public Criteria andRqqIsNull() {
            addCriterion("rqq is null");
            return (Criteria) this;
        }

        public Criteria andRqqIsNotNull() {
            addCriterion("rqq is not null");
            return (Criteria) this;
        }

        public Criteria andRqqEqualTo(String value) {
            addCriterion("rqq =", value, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqNotEqualTo(String value) {
            addCriterion("rqq <>", value, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqGreaterThan(String value) {
            addCriterion("rqq >", value, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqGreaterThanOrEqualTo(String value) {
            addCriterion("rqq >=", value, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqLessThan(String value) {
            addCriterion("rqq <", value, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqLessThanOrEqualTo(String value) {
            addCriterion("rqq <=", value, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqLike(String value) {
            addCriterion("rqq like", value, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqNotLike(String value) {
            addCriterion("rqq not like", value, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqIn(List<String> values) {
            addCriterion("rqq in", values, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqNotIn(List<String> values) {
            addCriterion("rqq not in", values, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqBetween(String value1, String value2) {
            addCriterion("rqq between", value1, value2, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqqNotBetween(String value1, String value2) {
            addCriterion("rqq not between", value1, value2, "rqq");
            return (Criteria) this;
        }

        public Criteria andRqzIsNull() {
            addCriterion("rqz is null");
            return (Criteria) this;
        }

        public Criteria andRqzIsNotNull() {
            addCriterion("rqz is not null");
            return (Criteria) this;
        }

        public Criteria andRqzEqualTo(String value) {
            addCriterion("rqz =", value, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzNotEqualTo(String value) {
            addCriterion("rqz <>", value, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzGreaterThan(String value) {
            addCriterion("rqz >", value, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzGreaterThanOrEqualTo(String value) {
            addCriterion("rqz >=", value, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzLessThan(String value) {
            addCriterion("rqz <", value, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzLessThanOrEqualTo(String value) {
            addCriterion("rqz <=", value, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzLike(String value) {
            addCriterion("rqz like", value, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzNotLike(String value) {
            addCriterion("rqz not like", value, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzIn(List<String> values) {
            addCriterion("rqz in", values, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzNotIn(List<String> values) {
            addCriterion("rqz not in", values, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzBetween(String value1, String value2) {
            addCriterion("rqz between", value1, value2, "rqz");
            return (Criteria) this;
        }

        public Criteria andRqzNotBetween(String value1, String value2) {
            addCriterion("rqz not between", value1, value2, "rqz");
            return (Criteria) this;
        }

        public Criteria andJeIsNull() {
            addCriterion("je is null");
            return (Criteria) this;
        }

        public Criteria andJeIsNotNull() {
            addCriterion("je is not null");
            return (Criteria) this;
        }

        public Criteria andJeEqualTo(BigDecimal value) {
            addCriterion("je =", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotEqualTo(BigDecimal value) {
            addCriterion("je <>", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThan(BigDecimal value) {
            addCriterion("je >", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("je >=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThan(BigDecimal value) {
            addCriterion("je <", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("je <=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeIn(List<BigDecimal> values) {
            addCriterion("je in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotIn(List<BigDecimal> values) {
            addCriterion("je not in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("je between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("je not between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andSlIsNull() {
            addCriterion("sl is null");
            return (Criteria) this;
        }

        public Criteria andSlIsNotNull() {
            addCriterion("sl is not null");
            return (Criteria) this;
        }

        public Criteria andSlEqualTo(BigDecimal value) {
            addCriterion("sl =", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotEqualTo(BigDecimal value) {
            addCriterion("sl <>", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThan(BigDecimal value) {
            addCriterion("sl >", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sl >=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThan(BigDecimal value) {
            addCriterion("sl <", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sl <=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlIn(List<BigDecimal> values) {
            addCriterion("sl in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotIn(List<BigDecimal> values) {
            addCriterion("sl not in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sl between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sl not between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andSeIsNull() {
            addCriterion("se is null");
            return (Criteria) this;
        }

        public Criteria andSeIsNotNull() {
            addCriterion("se is not null");
            return (Criteria) this;
        }

        public Criteria andSeEqualTo(BigDecimal value) {
            addCriterion("se =", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeNotEqualTo(BigDecimal value) {
            addCriterion("se <>", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeGreaterThan(BigDecimal value) {
            addCriterion("se >", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("se >=", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeLessThan(BigDecimal value) {
            addCriterion("se <", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("se <=", value, "se");
            return (Criteria) this;
        }

        public Criteria andSeIn(List<BigDecimal> values) {
            addCriterion("se in", values, "se");
            return (Criteria) this;
        }

        public Criteria andSeNotIn(List<BigDecimal> values) {
            addCriterion("se not in", values, "se");
            return (Criteria) this;
        }

        public Criteria andSeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("se between", value1, value2, "se");
            return (Criteria) this;
        }

        public Criteria andSeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("se not between", value1, value2, "se");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detail1
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 16 15:17:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detail1
     *
     * @mbg.generated Tue Apr 16 15:17:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}