package cn.yokaya.invoice.db.entity;

import java.math.BigDecimal;

public class Detail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.seq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private Integer seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.invoice_seq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private Integer invoiceSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.wwmc
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String wwmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.ggxh
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String ggxh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.dw
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String dw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.count
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private BigDecimal count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.dj
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private BigDecimal dj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.je
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private BigDecimal je;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.sl
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private BigDecimal sl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detail.se
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private BigDecimal se;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.seq
	 * @return  the value of detail.seq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public Integer getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.seq
	 * @param seq  the value for detail.seq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.invoice_seq
	 * @return  the value of detail.invoice_seq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public Integer getInvoiceSeq() {
		return invoiceSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.invoice_seq
	 * @param invoiceSeq  the value for detail.invoice_seq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setInvoiceSeq(Integer invoiceSeq) {
		this.invoiceSeq = invoiceSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.wwmc
	 * @return  the value of detail.wwmc
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getWwmc() {
		return wwmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.wwmc
	 * @param wwmc  the value for detail.wwmc
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setWwmc(String wwmc) {
		this.wwmc = wwmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.ggxh
	 * @return  the value of detail.ggxh
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getGgxh() {
		return ggxh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.ggxh
	 * @param ggxh  the value for detail.ggxh
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setGgxh(String ggxh) {
		this.ggxh = ggxh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.dw
	 * @return  the value of detail.dw
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getDw() {
		return dw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.dw
	 * @param dw  the value for detail.dw
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setDw(String dw) {
		this.dw = dw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.count
	 * @return  the value of detail.count
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public BigDecimal getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.count
	 * @param count  the value for detail.count
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setCount(BigDecimal count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.dj
	 * @return  the value of detail.dj
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public BigDecimal getDj() {
		return dj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.dj
	 * @param dj  the value for detail.dj
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setDj(BigDecimal dj) {
		this.dj = dj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.je
	 * @return  the value of detail.je
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public BigDecimal getJe() {
		return je;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.je
	 * @param je  the value for detail.je
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setJe(BigDecimal je) {
		this.je = je;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.sl
	 * @return  the value of detail.sl
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public BigDecimal getSl() {
		return sl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.sl
	 * @param sl  the value for detail.sl
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setSl(BigDecimal sl) {
		this.sl = sl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detail.se
	 * @return  the value of detail.se
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public BigDecimal getSe() {
		return se;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detail.se
	 * @param se  the value for detail.se
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setSe(BigDecimal se) {
		this.se = se;
	}
}