package cn.yokaya.invoice.db.entity;

import java.math.BigDecimal;

public class Invoice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.seq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private Integer seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.title
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.jqbh
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String jqbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.fpdm
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String fpdm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.fphm
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String fphm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.kprq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String kprq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.jym
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String jym;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.mc1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String mc1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.nsrsbh1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String nsrsbh1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.dzdh1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String dzdh1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.khhjzh1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String khhjzh1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.mmq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String mmq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.hjje
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private BigDecimal hjje;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.hjse
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private BigDecimal hjse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.jshjdx
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String jshjdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.jshjxx
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private BigDecimal jshjxx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.mc2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String mc2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.nsrsbh2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String nsrsbh2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.dzdh2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String dzdh2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.khhjzh2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String khhjzh2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.skr
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String skr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.fh
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String fh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.kpr
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String kpr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.file
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String file;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.upload_time
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String uploadTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.type
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	private String type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.seq
	 * @return  the value of invoice.seq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public Integer getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.seq
	 * @param seq  the value for invoice.seq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.title
	 * @return  the value of invoice.title
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.title
	 * @param title  the value for invoice.title
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.jqbh
	 * @return  the value of invoice.jqbh
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getJqbh() {
		return jqbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.jqbh
	 * @param jqbh  the value for invoice.jqbh
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setJqbh(String jqbh) {
		this.jqbh = jqbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.fpdm
	 * @return  the value of invoice.fpdm
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getFpdm() {
		return fpdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.fpdm
	 * @param fpdm  the value for invoice.fpdm
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setFpdm(String fpdm) {
		this.fpdm = fpdm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.fphm
	 * @return  the value of invoice.fphm
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getFphm() {
		return fphm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.fphm
	 * @param fphm  the value for invoice.fphm
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setFphm(String fphm) {
		this.fphm = fphm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.kprq
	 * @return  the value of invoice.kprq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getKprq() {
		return kprq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.kprq
	 * @param kprq  the value for invoice.kprq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setKprq(String kprq) {
		this.kprq = kprq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.jym
	 * @return  the value of invoice.jym
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getJym() {
		return jym;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.jym
	 * @param jym  the value for invoice.jym
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setJym(String jym) {
		this.jym = jym;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.mc1
	 * @return  the value of invoice.mc1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getMc1() {
		return mc1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.mc1
	 * @param mc1  the value for invoice.mc1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setMc1(String mc1) {
		this.mc1 = mc1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.nsrsbh1
	 * @return  the value of invoice.nsrsbh1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getNsrsbh1() {
		return nsrsbh1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.nsrsbh1
	 * @param nsrsbh1  the value for invoice.nsrsbh1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setNsrsbh1(String nsrsbh1) {
		this.nsrsbh1 = nsrsbh1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.dzdh1
	 * @return  the value of invoice.dzdh1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getDzdh1() {
		return dzdh1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.dzdh1
	 * @param dzdh1  the value for invoice.dzdh1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setDzdh1(String dzdh1) {
		this.dzdh1 = dzdh1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.khhjzh1
	 * @return  the value of invoice.khhjzh1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getKhhjzh1() {
		return khhjzh1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.khhjzh1
	 * @param khhjzh1  the value for invoice.khhjzh1
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setKhhjzh1(String khhjzh1) {
		this.khhjzh1 = khhjzh1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.mmq
	 * @return  the value of invoice.mmq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getMmq() {
		return mmq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.mmq
	 * @param mmq  the value for invoice.mmq
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setMmq(String mmq) {
		this.mmq = mmq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.hjje
	 * @return  the value of invoice.hjje
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public BigDecimal getHjje() {
		return hjje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.hjje
	 * @param hjje  the value for invoice.hjje
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setHjje(BigDecimal hjje) {
		this.hjje = hjje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.hjse
	 * @return  the value of invoice.hjse
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public BigDecimal getHjse() {
		return hjse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.hjse
	 * @param hjse  the value for invoice.hjse
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setHjse(BigDecimal hjse) {
		this.hjse = hjse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.jshjdx
	 * @return  the value of invoice.jshjdx
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getJshjdx() {
		return jshjdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.jshjdx
	 * @param jshjdx  the value for invoice.jshjdx
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setJshjdx(String jshjdx) {
		this.jshjdx = jshjdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.jshjxx
	 * @return  the value of invoice.jshjxx
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public BigDecimal getJshjxx() {
		return jshjxx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.jshjxx
	 * @param jshjxx  the value for invoice.jshjxx
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setJshjxx(BigDecimal jshjxx) {
		this.jshjxx = jshjxx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.mc2
	 * @return  the value of invoice.mc2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getMc2() {
		return mc2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.mc2
	 * @param mc2  the value for invoice.mc2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setMc2(String mc2) {
		this.mc2 = mc2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.nsrsbh2
	 * @return  the value of invoice.nsrsbh2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getNsrsbh2() {
		return nsrsbh2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.nsrsbh2
	 * @param nsrsbh2  the value for invoice.nsrsbh2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setNsrsbh2(String nsrsbh2) {
		this.nsrsbh2 = nsrsbh2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.dzdh2
	 * @return  the value of invoice.dzdh2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getDzdh2() {
		return dzdh2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.dzdh2
	 * @param dzdh2  the value for invoice.dzdh2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setDzdh2(String dzdh2) {
		this.dzdh2 = dzdh2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.khhjzh2
	 * @return  the value of invoice.khhjzh2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getKhhjzh2() {
		return khhjzh2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.khhjzh2
	 * @param khhjzh2  the value for invoice.khhjzh2
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setKhhjzh2(String khhjzh2) {
		this.khhjzh2 = khhjzh2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.skr
	 * @return  the value of invoice.skr
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getSkr() {
		return skr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.skr
	 * @param skr  the value for invoice.skr
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setSkr(String skr) {
		this.skr = skr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.fh
	 * @return  the value of invoice.fh
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getFh() {
		return fh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.fh
	 * @param fh  the value for invoice.fh
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setFh(String fh) {
		this.fh = fh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.kpr
	 * @return  the value of invoice.kpr
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getKpr() {
		return kpr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.kpr
	 * @param kpr  the value for invoice.kpr
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setKpr(String kpr) {
		this.kpr = kpr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.file
	 * @return  the value of invoice.file
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getFile() {
		return file;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.file
	 * @param file  the value for invoice.file
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setFile(String file) {
		this.file = file;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.upload_time
	 * @return  the value of invoice.upload_time
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getUploadTime() {
		return uploadTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.upload_time
	 * @param uploadTime  the value for invoice.upload_time
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setUploadTime(String uploadTime) {
		this.uploadTime = uploadTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.type
	 * @return  the value of invoice.type
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.type
	 * @param type  the value for invoice.type
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setType(String type) {
		this.type = type;
	}
}