package cn.yokaya.invoice.db.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class InvoiceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public InvoiceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSeqIsNull() {
			addCriterion("seq is null");
			return (Criteria) this;
		}

		public Criteria andSeqIsNotNull() {
			addCriterion("seq is not null");
			return (Criteria) this;
		}

		public Criteria andSeqEqualTo(Integer value) {
			addCriterion("seq =", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotEqualTo(Integer value) {
			addCriterion("seq <>", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThan(Integer value) {
			addCriterion("seq >", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThanOrEqualTo(Integer value) {
			addCriterion("seq >=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThan(Integer value) {
			addCriterion("seq <", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThanOrEqualTo(Integer value) {
			addCriterion("seq <=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqIn(List<Integer> values) {
			addCriterion("seq in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotIn(List<Integer> values) {
			addCriterion("seq not in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqBetween(Integer value1, Integer value2) {
			addCriterion("seq between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotBetween(Integer value1, Integer value2) {
			addCriterion("seq not between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andJqbhIsNull() {
			addCriterion("jqbh is null");
			return (Criteria) this;
		}

		public Criteria andJqbhIsNotNull() {
			addCriterion("jqbh is not null");
			return (Criteria) this;
		}

		public Criteria andJqbhEqualTo(String value) {
			addCriterion("jqbh =", value, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhNotEqualTo(String value) {
			addCriterion("jqbh <>", value, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhGreaterThan(String value) {
			addCriterion("jqbh >", value, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhGreaterThanOrEqualTo(String value) {
			addCriterion("jqbh >=", value, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhLessThan(String value) {
			addCriterion("jqbh <", value, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhLessThanOrEqualTo(String value) {
			addCriterion("jqbh <=", value, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhLike(String value) {
			addCriterion("jqbh like", value, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhNotLike(String value) {
			addCriterion("jqbh not like", value, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhIn(List<String> values) {
			addCriterion("jqbh in", values, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhNotIn(List<String> values) {
			addCriterion("jqbh not in", values, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhBetween(String value1, String value2) {
			addCriterion("jqbh between", value1, value2, "jqbh");
			return (Criteria) this;
		}

		public Criteria andJqbhNotBetween(String value1, String value2) {
			addCriterion("jqbh not between", value1, value2, "jqbh");
			return (Criteria) this;
		}

		public Criteria andFpdmIsNull() {
			addCriterion("fpdm is null");
			return (Criteria) this;
		}

		public Criteria andFpdmIsNotNull() {
			addCriterion("fpdm is not null");
			return (Criteria) this;
		}

		public Criteria andFpdmEqualTo(String value) {
			addCriterion("fpdm =", value, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmNotEqualTo(String value) {
			addCriterion("fpdm <>", value, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmGreaterThan(String value) {
			addCriterion("fpdm >", value, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmGreaterThanOrEqualTo(String value) {
			addCriterion("fpdm >=", value, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmLessThan(String value) {
			addCriterion("fpdm <", value, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmLessThanOrEqualTo(String value) {
			addCriterion("fpdm <=", value, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmLike(String value) {
			addCriterion("fpdm like", value, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmNotLike(String value) {
			addCriterion("fpdm not like", value, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmIn(List<String> values) {
			addCriterion("fpdm in", values, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmNotIn(List<String> values) {
			addCriterion("fpdm not in", values, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmBetween(String value1, String value2) {
			addCriterion("fpdm between", value1, value2, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFpdmNotBetween(String value1, String value2) {
			addCriterion("fpdm not between", value1, value2, "fpdm");
			return (Criteria) this;
		}

		public Criteria andFphmIsNull() {
			addCriterion("fphm is null");
			return (Criteria) this;
		}

		public Criteria andFphmIsNotNull() {
			addCriterion("fphm is not null");
			return (Criteria) this;
		}

		public Criteria andFphmEqualTo(String value) {
			addCriterion("fphm =", value, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmNotEqualTo(String value) {
			addCriterion("fphm <>", value, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmGreaterThan(String value) {
			addCriterion("fphm >", value, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmGreaterThanOrEqualTo(String value) {
			addCriterion("fphm >=", value, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmLessThan(String value) {
			addCriterion("fphm <", value, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmLessThanOrEqualTo(String value) {
			addCriterion("fphm <=", value, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmLike(String value) {
			addCriterion("fphm like", value, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmNotLike(String value) {
			addCriterion("fphm not like", value, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmIn(List<String> values) {
			addCriterion("fphm in", values, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmNotIn(List<String> values) {
			addCriterion("fphm not in", values, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmBetween(String value1, String value2) {
			addCriterion("fphm between", value1, value2, "fphm");
			return (Criteria) this;
		}

		public Criteria andFphmNotBetween(String value1, String value2) {
			addCriterion("fphm not between", value1, value2, "fphm");
			return (Criteria) this;
		}

		public Criteria andKprqIsNull() {
			addCriterion("kprq is null");
			return (Criteria) this;
		}

		public Criteria andKprqIsNotNull() {
			addCriterion("kprq is not null");
			return (Criteria) this;
		}

		public Criteria andKprqEqualTo(String value) {
			addCriterion("kprq =", value, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqNotEqualTo(String value) {
			addCriterion("kprq <>", value, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqGreaterThan(String value) {
			addCriterion("kprq >", value, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqGreaterThanOrEqualTo(String value) {
			addCriterion("kprq >=", value, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqLessThan(String value) {
			addCriterion("kprq <", value, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqLessThanOrEqualTo(String value) {
			addCriterion("kprq <=", value, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqLike(String value) {
			addCriterion("kprq like", value, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqNotLike(String value) {
			addCriterion("kprq not like", value, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqIn(List<String> values) {
			addCriterion("kprq in", values, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqNotIn(List<String> values) {
			addCriterion("kprq not in", values, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqBetween(String value1, String value2) {
			addCriterion("kprq between", value1, value2, "kprq");
			return (Criteria) this;
		}

		public Criteria andKprqNotBetween(String value1, String value2) {
			addCriterion("kprq not between", value1, value2, "kprq");
			return (Criteria) this;
		}

		public Criteria andJymIsNull() {
			addCriterion("jym is null");
			return (Criteria) this;
		}

		public Criteria andJymIsNotNull() {
			addCriterion("jym is not null");
			return (Criteria) this;
		}

		public Criteria andJymEqualTo(String value) {
			addCriterion("jym =", value, "jym");
			return (Criteria) this;
		}

		public Criteria andJymNotEqualTo(String value) {
			addCriterion("jym <>", value, "jym");
			return (Criteria) this;
		}

		public Criteria andJymGreaterThan(String value) {
			addCriterion("jym >", value, "jym");
			return (Criteria) this;
		}

		public Criteria andJymGreaterThanOrEqualTo(String value) {
			addCriterion("jym >=", value, "jym");
			return (Criteria) this;
		}

		public Criteria andJymLessThan(String value) {
			addCriterion("jym <", value, "jym");
			return (Criteria) this;
		}

		public Criteria andJymLessThanOrEqualTo(String value) {
			addCriterion("jym <=", value, "jym");
			return (Criteria) this;
		}

		public Criteria andJymLike(String value) {
			addCriterion("jym like", value, "jym");
			return (Criteria) this;
		}

		public Criteria andJymNotLike(String value) {
			addCriterion("jym not like", value, "jym");
			return (Criteria) this;
		}

		public Criteria andJymIn(List<String> values) {
			addCriterion("jym in", values, "jym");
			return (Criteria) this;
		}

		public Criteria andJymNotIn(List<String> values) {
			addCriterion("jym not in", values, "jym");
			return (Criteria) this;
		}

		public Criteria andJymBetween(String value1, String value2) {
			addCriterion("jym between", value1, value2, "jym");
			return (Criteria) this;
		}

		public Criteria andJymNotBetween(String value1, String value2) {
			addCriterion("jym not between", value1, value2, "jym");
			return (Criteria) this;
		}

		public Criteria andMc1IsNull() {
			addCriterion("mc1 is null");
			return (Criteria) this;
		}

		public Criteria andMc1IsNotNull() {
			addCriterion("mc1 is not null");
			return (Criteria) this;
		}

		public Criteria andMc1EqualTo(String value) {
			addCriterion("mc1 =", value, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1NotEqualTo(String value) {
			addCriterion("mc1 <>", value, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1GreaterThan(String value) {
			addCriterion("mc1 >", value, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1GreaterThanOrEqualTo(String value) {
			addCriterion("mc1 >=", value, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1LessThan(String value) {
			addCriterion("mc1 <", value, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1LessThanOrEqualTo(String value) {
			addCriterion("mc1 <=", value, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1Like(String value) {
			addCriterion("mc1 like", value, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1NotLike(String value) {
			addCriterion("mc1 not like", value, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1In(List<String> values) {
			addCriterion("mc1 in", values, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1NotIn(List<String> values) {
			addCriterion("mc1 not in", values, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1Between(String value1, String value2) {
			addCriterion("mc1 between", value1, value2, "mc1");
			return (Criteria) this;
		}

		public Criteria andMc1NotBetween(String value1, String value2) {
			addCriterion("mc1 not between", value1, value2, "mc1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1IsNull() {
			addCriterion("nsrsbh1 is null");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1IsNotNull() {
			addCriterion("nsrsbh1 is not null");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1EqualTo(String value) {
			addCriterion("nsrsbh1 =", value, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1NotEqualTo(String value) {
			addCriterion("nsrsbh1 <>", value, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1GreaterThan(String value) {
			addCriterion("nsrsbh1 >", value, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1GreaterThanOrEqualTo(String value) {
			addCriterion("nsrsbh1 >=", value, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1LessThan(String value) {
			addCriterion("nsrsbh1 <", value, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1LessThanOrEqualTo(String value) {
			addCriterion("nsrsbh1 <=", value, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1Like(String value) {
			addCriterion("nsrsbh1 like", value, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1NotLike(String value) {
			addCriterion("nsrsbh1 not like", value, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1In(List<String> values) {
			addCriterion("nsrsbh1 in", values, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1NotIn(List<String> values) {
			addCriterion("nsrsbh1 not in", values, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1Between(String value1, String value2) {
			addCriterion("nsrsbh1 between", value1, value2, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andNsrsbh1NotBetween(String value1, String value2) {
			addCriterion("nsrsbh1 not between", value1, value2, "nsrsbh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1IsNull() {
			addCriterion("dzdh1 is null");
			return (Criteria) this;
		}

		public Criteria andDzdh1IsNotNull() {
			addCriterion("dzdh1 is not null");
			return (Criteria) this;
		}

		public Criteria andDzdh1EqualTo(String value) {
			addCriterion("dzdh1 =", value, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1NotEqualTo(String value) {
			addCriterion("dzdh1 <>", value, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1GreaterThan(String value) {
			addCriterion("dzdh1 >", value, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1GreaterThanOrEqualTo(String value) {
			addCriterion("dzdh1 >=", value, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1LessThan(String value) {
			addCriterion("dzdh1 <", value, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1LessThanOrEqualTo(String value) {
			addCriterion("dzdh1 <=", value, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1Like(String value) {
			addCriterion("dzdh1 like", value, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1NotLike(String value) {
			addCriterion("dzdh1 not like", value, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1In(List<String> values) {
			addCriterion("dzdh1 in", values, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1NotIn(List<String> values) {
			addCriterion("dzdh1 not in", values, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1Between(String value1, String value2) {
			addCriterion("dzdh1 between", value1, value2, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andDzdh1NotBetween(String value1, String value2) {
			addCriterion("dzdh1 not between", value1, value2, "dzdh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1IsNull() {
			addCriterion("khhjzh1 is null");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1IsNotNull() {
			addCriterion("khhjzh1 is not null");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1EqualTo(String value) {
			addCriterion("khhjzh1 =", value, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1NotEqualTo(String value) {
			addCriterion("khhjzh1 <>", value, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1GreaterThan(String value) {
			addCriterion("khhjzh1 >", value, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1GreaterThanOrEqualTo(String value) {
			addCriterion("khhjzh1 >=", value, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1LessThan(String value) {
			addCriterion("khhjzh1 <", value, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1LessThanOrEqualTo(String value) {
			addCriterion("khhjzh1 <=", value, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1Like(String value) {
			addCriterion("khhjzh1 like", value, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1NotLike(String value) {
			addCriterion("khhjzh1 not like", value, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1In(List<String> values) {
			addCriterion("khhjzh1 in", values, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1NotIn(List<String> values) {
			addCriterion("khhjzh1 not in", values, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1Between(String value1, String value2) {
			addCriterion("khhjzh1 between", value1, value2, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andKhhjzh1NotBetween(String value1, String value2) {
			addCriterion("khhjzh1 not between", value1, value2, "khhjzh1");
			return (Criteria) this;
		}

		public Criteria andMmqIsNull() {
			addCriterion("mmq is null");
			return (Criteria) this;
		}

		public Criteria andMmqIsNotNull() {
			addCriterion("mmq is not null");
			return (Criteria) this;
		}

		public Criteria andMmqEqualTo(String value) {
			addCriterion("mmq =", value, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqNotEqualTo(String value) {
			addCriterion("mmq <>", value, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqGreaterThan(String value) {
			addCriterion("mmq >", value, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqGreaterThanOrEqualTo(String value) {
			addCriterion("mmq >=", value, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqLessThan(String value) {
			addCriterion("mmq <", value, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqLessThanOrEqualTo(String value) {
			addCriterion("mmq <=", value, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqLike(String value) {
			addCriterion("mmq like", value, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqNotLike(String value) {
			addCriterion("mmq not like", value, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqIn(List<String> values) {
			addCriterion("mmq in", values, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqNotIn(List<String> values) {
			addCriterion("mmq not in", values, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqBetween(String value1, String value2) {
			addCriterion("mmq between", value1, value2, "mmq");
			return (Criteria) this;
		}

		public Criteria andMmqNotBetween(String value1, String value2) {
			addCriterion("mmq not between", value1, value2, "mmq");
			return (Criteria) this;
		}

		public Criteria andHjjeIsNull() {
			addCriterion("hjje is null");
			return (Criteria) this;
		}

		public Criteria andHjjeIsNotNull() {
			addCriterion("hjje is not null");
			return (Criteria) this;
		}

		public Criteria andHjjeEqualTo(BigDecimal value) {
			addCriterion("hjje =", value, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjjeNotEqualTo(BigDecimal value) {
			addCriterion("hjje <>", value, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjjeGreaterThan(BigDecimal value) {
			addCriterion("hjje >", value, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjjeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("hjje >=", value, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjjeLessThan(BigDecimal value) {
			addCriterion("hjje <", value, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjjeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("hjje <=", value, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjjeIn(List<BigDecimal> values) {
			addCriterion("hjje in", values, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjjeNotIn(List<BigDecimal> values) {
			addCriterion("hjje not in", values, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjjeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("hjje between", value1, value2, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjjeNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("hjje not between", value1, value2, "hjje");
			return (Criteria) this;
		}

		public Criteria andHjseIsNull() {
			addCriterion("hjse is null");
			return (Criteria) this;
		}

		public Criteria andHjseIsNotNull() {
			addCriterion("hjse is not null");
			return (Criteria) this;
		}

		public Criteria andHjseEqualTo(BigDecimal value) {
			addCriterion("hjse =", value, "hjse");
			return (Criteria) this;
		}

		public Criteria andHjseNotEqualTo(BigDecimal value) {
			addCriterion("hjse <>", value, "hjse");
			return (Criteria) this;
		}

		public Criteria andHjseGreaterThan(BigDecimal value) {
			addCriterion("hjse >", value, "hjse");
			return (Criteria) this;
		}

		public Criteria andHjseGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("hjse >=", value, "hjse");
			return (Criteria) this;
		}

		public Criteria andHjseLessThan(BigDecimal value) {
			addCriterion("hjse <", value, "hjse");
			return (Criteria) this;
		}

		public Criteria andHjseLessThanOrEqualTo(BigDecimal value) {
			addCriterion("hjse <=", value, "hjse");
			return (Criteria) this;
		}

		public Criteria andHjseIn(List<BigDecimal> values) {
			addCriterion("hjse in", values, "hjse");
			return (Criteria) this;
		}

		public Criteria andHjseNotIn(List<BigDecimal> values) {
			addCriterion("hjse not in", values, "hjse");
			return (Criteria) this;
		}

		public Criteria andHjseBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("hjse between", value1, value2, "hjse");
			return (Criteria) this;
		}

		public Criteria andHjseNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("hjse not between", value1, value2, "hjse");
			return (Criteria) this;
		}

		public Criteria andJshjdxIsNull() {
			addCriterion("jshjdx is null");
			return (Criteria) this;
		}

		public Criteria andJshjdxIsNotNull() {
			addCriterion("jshjdx is not null");
			return (Criteria) this;
		}

		public Criteria andJshjdxEqualTo(String value) {
			addCriterion("jshjdx =", value, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxNotEqualTo(String value) {
			addCriterion("jshjdx <>", value, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxGreaterThan(String value) {
			addCriterion("jshjdx >", value, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxGreaterThanOrEqualTo(String value) {
			addCriterion("jshjdx >=", value, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxLessThan(String value) {
			addCriterion("jshjdx <", value, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxLessThanOrEqualTo(String value) {
			addCriterion("jshjdx <=", value, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxLike(String value) {
			addCriterion("jshjdx like", value, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxNotLike(String value) {
			addCriterion("jshjdx not like", value, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxIn(List<String> values) {
			addCriterion("jshjdx in", values, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxNotIn(List<String> values) {
			addCriterion("jshjdx not in", values, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxBetween(String value1, String value2) {
			addCriterion("jshjdx between", value1, value2, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjdxNotBetween(String value1, String value2) {
			addCriterion("jshjdx not between", value1, value2, "jshjdx");
			return (Criteria) this;
		}

		public Criteria andJshjxxIsNull() {
			addCriterion("jshjxx is null");
			return (Criteria) this;
		}

		public Criteria andJshjxxIsNotNull() {
			addCriterion("jshjxx is not null");
			return (Criteria) this;
		}

		public Criteria andJshjxxEqualTo(BigDecimal value) {
			addCriterion("jshjxx =", value, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andJshjxxNotEqualTo(BigDecimal value) {
			addCriterion("jshjxx <>", value, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andJshjxxGreaterThan(BigDecimal value) {
			addCriterion("jshjxx >", value, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andJshjxxGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("jshjxx >=", value, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andJshjxxLessThan(BigDecimal value) {
			addCriterion("jshjxx <", value, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andJshjxxLessThanOrEqualTo(BigDecimal value) {
			addCriterion("jshjxx <=", value, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andJshjxxIn(List<BigDecimal> values) {
			addCriterion("jshjxx in", values, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andJshjxxNotIn(List<BigDecimal> values) {
			addCriterion("jshjxx not in", values, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andJshjxxBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("jshjxx between", value1, value2, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andJshjxxNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("jshjxx not between", value1, value2, "jshjxx");
			return (Criteria) this;
		}

		public Criteria andMc2IsNull() {
			addCriterion("mc2 is null");
			return (Criteria) this;
		}

		public Criteria andMc2IsNotNull() {
			addCriterion("mc2 is not null");
			return (Criteria) this;
		}

		public Criteria andMc2EqualTo(String value) {
			addCriterion("mc2 =", value, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2NotEqualTo(String value) {
			addCriterion("mc2 <>", value, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2GreaterThan(String value) {
			addCriterion("mc2 >", value, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2GreaterThanOrEqualTo(String value) {
			addCriterion("mc2 >=", value, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2LessThan(String value) {
			addCriterion("mc2 <", value, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2LessThanOrEqualTo(String value) {
			addCriterion("mc2 <=", value, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2Like(String value) {
			addCriterion("mc2 like", value, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2NotLike(String value) {
			addCriterion("mc2 not like", value, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2In(List<String> values) {
			addCriterion("mc2 in", values, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2NotIn(List<String> values) {
			addCriterion("mc2 not in", values, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2Between(String value1, String value2) {
			addCriterion("mc2 between", value1, value2, "mc2");
			return (Criteria) this;
		}

		public Criteria andMc2NotBetween(String value1, String value2) {
			addCriterion("mc2 not between", value1, value2, "mc2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2IsNull() {
			addCriterion("nsrsbh2 is null");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2IsNotNull() {
			addCriterion("nsrsbh2 is not null");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2EqualTo(String value) {
			addCriterion("nsrsbh2 =", value, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2NotEqualTo(String value) {
			addCriterion("nsrsbh2 <>", value, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2GreaterThan(String value) {
			addCriterion("nsrsbh2 >", value, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2GreaterThanOrEqualTo(String value) {
			addCriterion("nsrsbh2 >=", value, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2LessThan(String value) {
			addCriterion("nsrsbh2 <", value, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2LessThanOrEqualTo(String value) {
			addCriterion("nsrsbh2 <=", value, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2Like(String value) {
			addCriterion("nsrsbh2 like", value, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2NotLike(String value) {
			addCriterion("nsrsbh2 not like", value, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2In(List<String> values) {
			addCriterion("nsrsbh2 in", values, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2NotIn(List<String> values) {
			addCriterion("nsrsbh2 not in", values, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2Between(String value1, String value2) {
			addCriterion("nsrsbh2 between", value1, value2, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andNsrsbh2NotBetween(String value1, String value2) {
			addCriterion("nsrsbh2 not between", value1, value2, "nsrsbh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2IsNull() {
			addCriterion("dzdh2 is null");
			return (Criteria) this;
		}

		public Criteria andDzdh2IsNotNull() {
			addCriterion("dzdh2 is not null");
			return (Criteria) this;
		}

		public Criteria andDzdh2EqualTo(String value) {
			addCriterion("dzdh2 =", value, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2NotEqualTo(String value) {
			addCriterion("dzdh2 <>", value, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2GreaterThan(String value) {
			addCriterion("dzdh2 >", value, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2GreaterThanOrEqualTo(String value) {
			addCriterion("dzdh2 >=", value, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2LessThan(String value) {
			addCriterion("dzdh2 <", value, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2LessThanOrEqualTo(String value) {
			addCriterion("dzdh2 <=", value, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2Like(String value) {
			addCriterion("dzdh2 like", value, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2NotLike(String value) {
			addCriterion("dzdh2 not like", value, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2In(List<String> values) {
			addCriterion("dzdh2 in", values, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2NotIn(List<String> values) {
			addCriterion("dzdh2 not in", values, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2Between(String value1, String value2) {
			addCriterion("dzdh2 between", value1, value2, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andDzdh2NotBetween(String value1, String value2) {
			addCriterion("dzdh2 not between", value1, value2, "dzdh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2IsNull() {
			addCriterion("khhjzh2 is null");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2IsNotNull() {
			addCriterion("khhjzh2 is not null");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2EqualTo(String value) {
			addCriterion("khhjzh2 =", value, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2NotEqualTo(String value) {
			addCriterion("khhjzh2 <>", value, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2GreaterThan(String value) {
			addCriterion("khhjzh2 >", value, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2GreaterThanOrEqualTo(String value) {
			addCriterion("khhjzh2 >=", value, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2LessThan(String value) {
			addCriterion("khhjzh2 <", value, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2LessThanOrEqualTo(String value) {
			addCriterion("khhjzh2 <=", value, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2Like(String value) {
			addCriterion("khhjzh2 like", value, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2NotLike(String value) {
			addCriterion("khhjzh2 not like", value, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2In(List<String> values) {
			addCriterion("khhjzh2 in", values, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2NotIn(List<String> values) {
			addCriterion("khhjzh2 not in", values, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2Between(String value1, String value2) {
			addCriterion("khhjzh2 between", value1, value2, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andKhhjzh2NotBetween(String value1, String value2) {
			addCriterion("khhjzh2 not between", value1, value2, "khhjzh2");
			return (Criteria) this;
		}

		public Criteria andSkrIsNull() {
			addCriterion("skr is null");
			return (Criteria) this;
		}

		public Criteria andSkrIsNotNull() {
			addCriterion("skr is not null");
			return (Criteria) this;
		}

		public Criteria andSkrEqualTo(String value) {
			addCriterion("skr =", value, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrNotEqualTo(String value) {
			addCriterion("skr <>", value, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrGreaterThan(String value) {
			addCriterion("skr >", value, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrGreaterThanOrEqualTo(String value) {
			addCriterion("skr >=", value, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrLessThan(String value) {
			addCriterion("skr <", value, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrLessThanOrEqualTo(String value) {
			addCriterion("skr <=", value, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrLike(String value) {
			addCriterion("skr like", value, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrNotLike(String value) {
			addCriterion("skr not like", value, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrIn(List<String> values) {
			addCriterion("skr in", values, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrNotIn(List<String> values) {
			addCriterion("skr not in", values, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrBetween(String value1, String value2) {
			addCriterion("skr between", value1, value2, "skr");
			return (Criteria) this;
		}

		public Criteria andSkrNotBetween(String value1, String value2) {
			addCriterion("skr not between", value1, value2, "skr");
			return (Criteria) this;
		}

		public Criteria andFhIsNull() {
			addCriterion("fh is null");
			return (Criteria) this;
		}

		public Criteria andFhIsNotNull() {
			addCriterion("fh is not null");
			return (Criteria) this;
		}

		public Criteria andFhEqualTo(String value) {
			addCriterion("fh =", value, "fh");
			return (Criteria) this;
		}

		public Criteria andFhNotEqualTo(String value) {
			addCriterion("fh <>", value, "fh");
			return (Criteria) this;
		}

		public Criteria andFhGreaterThan(String value) {
			addCriterion("fh >", value, "fh");
			return (Criteria) this;
		}

		public Criteria andFhGreaterThanOrEqualTo(String value) {
			addCriterion("fh >=", value, "fh");
			return (Criteria) this;
		}

		public Criteria andFhLessThan(String value) {
			addCriterion("fh <", value, "fh");
			return (Criteria) this;
		}

		public Criteria andFhLessThanOrEqualTo(String value) {
			addCriterion("fh <=", value, "fh");
			return (Criteria) this;
		}

		public Criteria andFhLike(String value) {
			addCriterion("fh like", value, "fh");
			return (Criteria) this;
		}

		public Criteria andFhNotLike(String value) {
			addCriterion("fh not like", value, "fh");
			return (Criteria) this;
		}

		public Criteria andFhIn(List<String> values) {
			addCriterion("fh in", values, "fh");
			return (Criteria) this;
		}

		public Criteria andFhNotIn(List<String> values) {
			addCriterion("fh not in", values, "fh");
			return (Criteria) this;
		}

		public Criteria andFhBetween(String value1, String value2) {
			addCriterion("fh between", value1, value2, "fh");
			return (Criteria) this;
		}

		public Criteria andFhNotBetween(String value1, String value2) {
			addCriterion("fh not between", value1, value2, "fh");
			return (Criteria) this;
		}

		public Criteria andKprIsNull() {
			addCriterion("kpr is null");
			return (Criteria) this;
		}

		public Criteria andKprIsNotNull() {
			addCriterion("kpr is not null");
			return (Criteria) this;
		}

		public Criteria andKprEqualTo(String value) {
			addCriterion("kpr =", value, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprNotEqualTo(String value) {
			addCriterion("kpr <>", value, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprGreaterThan(String value) {
			addCriterion("kpr >", value, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprGreaterThanOrEqualTo(String value) {
			addCriterion("kpr >=", value, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprLessThan(String value) {
			addCriterion("kpr <", value, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprLessThanOrEqualTo(String value) {
			addCriterion("kpr <=", value, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprLike(String value) {
			addCriterion("kpr like", value, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprNotLike(String value) {
			addCriterion("kpr not like", value, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprIn(List<String> values) {
			addCriterion("kpr in", values, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprNotIn(List<String> values) {
			addCriterion("kpr not in", values, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprBetween(String value1, String value2) {
			addCriterion("kpr between", value1, value2, "kpr");
			return (Criteria) this;
		}

		public Criteria andKprNotBetween(String value1, String value2) {
			addCriterion("kpr not between", value1, value2, "kpr");
			return (Criteria) this;
		}

		public Criteria andFileIsNull() {
			addCriterion("file is null");
			return (Criteria) this;
		}

		public Criteria andFileIsNotNull() {
			addCriterion("file is not null");
			return (Criteria) this;
		}

		public Criteria andFileEqualTo(String value) {
			addCriterion("file =", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileNotEqualTo(String value) {
			addCriterion("file <>", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileGreaterThan(String value) {
			addCriterion("file >", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileGreaterThanOrEqualTo(String value) {
			addCriterion("file >=", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileLessThan(String value) {
			addCriterion("file <", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileLessThanOrEqualTo(String value) {
			addCriterion("file <=", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileLike(String value) {
			addCriterion("file like", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileNotLike(String value) {
			addCriterion("file not like", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileIn(List<String> values) {
			addCriterion("file in", values, "file");
			return (Criteria) this;
		}

		public Criteria andFileNotIn(List<String> values) {
			addCriterion("file not in", values, "file");
			return (Criteria) this;
		}

		public Criteria andFileBetween(String value1, String value2) {
			addCriterion("file between", value1, value2, "file");
			return (Criteria) this;
		}

		public Criteria andFileNotBetween(String value1, String value2) {
			addCriterion("file not between", value1, value2, "file");
			return (Criteria) this;
		}

		public Criteria andUploadTimeIsNull() {
			addCriterion("upload_time is null");
			return (Criteria) this;
		}

		public Criteria andUploadTimeIsNotNull() {
			addCriterion("upload_time is not null");
			return (Criteria) this;
		}

		public Criteria andUploadTimeEqualTo(String value) {
			addCriterion("upload_time =", value, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeNotEqualTo(String value) {
			addCriterion("upload_time <>", value, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeGreaterThan(String value) {
			addCriterion("upload_time >", value, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeGreaterThanOrEqualTo(String value) {
			addCriterion("upload_time >=", value, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeLessThan(String value) {
			addCriterion("upload_time <", value, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeLessThanOrEqualTo(String value) {
			addCriterion("upload_time <=", value, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeLike(String value) {
			addCriterion("upload_time like", value, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeNotLike(String value) {
			addCriterion("upload_time not like", value, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeIn(List<String> values) {
			addCriterion("upload_time in", values, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeNotIn(List<String> values) {
			addCriterion("upload_time not in", values, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeBetween(String value1, String value2) {
			addCriterion("upload_time between", value1, value2, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andUploadTimeNotBetween(String value1, String value2) {
			addCriterion("upload_time not between", value1, value2, "uploadTime");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table invoice
	 * @mbg.generated  Tue Apr 16 15:17:06 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoice
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 12 17:50:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}